/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import dao.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;


public class TelaCadastro extends javax.swing.JInternalFrame {
    UsuarioController usuarioController;
    ArrayList<Usuario> listaUsuario;
    Usuario usuario;
  
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        setModelo();
        limpaCampos();
        
        usuarioController = new UsuarioController();  
        listaUsuario();
        this.setSize(595,680);
        this.setLocation(80,320);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtNumeroCarteira = new javax.swing.JTextField();
        txtTipoCarteira = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastro = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Usuarios");
        setVisible(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 90, 50, 16);

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });
        getContentPane().add(txtBairro);
        txtBairro.setBounds(160, 320, 260, 30);

        txtNumeroCarteira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCarteiraKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeroCarteira);
        txtNumeroCarteira.setBounds(160, 360, 260, 30);

        txtTipoCarteira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoCarteiraKeyTyped(evt);
            }
        });
        getContentPane().add(txtTipoCarteira);
        txtTipoCarteira.setBounds(160, 400, 260, 30);

        btnCadastrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(300, 460, 97, 30);

        btnLimpar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(180, 460, 90, 30);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Cidade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 240, 60, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 210, 49, 16);

        tblCadastro.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        tblCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadastro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 510, 560, 90);

        btnExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(490, 620, 80, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 50, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        jLabel11.setText("     Cadastro");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 24))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 10, 180, 37);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 70, 16);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 290, 70, 16);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Bairro:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 330, 70, 16);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Número Carteira:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 370, 120, 22);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("TipoCarteira:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 410, 87, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(160, 80, 260, 30);

        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfKeyTyped(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(160, 120, 260, 30);

        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(160, 160, 260, 30);

        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyTyped(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(160, 280, 260, 30);

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });
        getContentPane().add(txtEstado);
        txtEstado.setBounds(160, 200, 260, 30);

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeKeyTyped(evt);
            }
        });
        getContentPane().add(txtCidade);
        txtCidade.setBounds(160, 240, 260, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        if (evt.getKeyChar() == 10) {
            txtNumeroCarteira.grabFocus();
        }
    }//GEN-LAST:event_txtBairroKeyTyped

    private void txtNumeroCarteiraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCarteiraKeyTyped
        if (evt.getKeyChar() == 10) {
            txtTipoCarteira.grabFocus();
        }
    }//GEN-LAST:event_txtNumeroCarteiraKeyTyped

    private void txtTipoCarteiraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoCarteiraKeyTyped
        if (evt.getKeyChar() == 10) {
            btnCadastrar.grabFocus();
        }
    }//GEN-LAST:event_txtTipoCarteiraKeyTyped

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        addUsuario();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tblCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastroMouseClicked
        carregaUsuario();
    }//GEN-LAST:event_tblCadastroMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        deleteUsuario();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if (evt.getKeyChar() == 10) {
            txtCpf.grabFocus();
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyTyped
        if (evt.getKeyChar() == 10) {
            txtTelefone.grabFocus();
        }
    }//GEN-LAST:event_txtCpfKeyTyped

    private void txtTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyTyped
        if (evt.getKeyChar() == 10) {
            txtEstado.grabFocus();
        }
    }//GEN-LAST:event_txtTelefoneKeyTyped

    private void txtEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyTyped
        if (evt.getKeyChar() == 10) {
            txtBairro.grabFocus();
        }
    }//GEN-LAST:event_txtEnderecoKeyTyped

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
 
        
    
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyTyped
       if (evt.getKeyChar() == 10) {
            txtEndereco.grabFocus();
       }
    }//GEN-LAST:event_txtCidadeKeyTyped

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        if (evt.getKeyChar() == 10) {
             txtCidade.grabFocus();
        }
    }//GEN-LAST:event_txtEstadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCadastro;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumeroCarteira;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTipoCarteira;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel modelo;

    private void setModelo() {

        modelo = new DefaultTableModel();
        modelo.addColumn("idusuario");
        modelo.addColumn("nome");
        modelo.addColumn("cpf");
        modelo.addColumn("telefone");
        modelo.addColumn("estado");
        modelo.addColumn("cidade");
        modelo.addColumn("endereco");
        modelo.addColumn("bairro");
        modelo.addColumn("numerocarteira");
        modelo.addColumn("tipocarteira");
        tblCadastro.setModel(modelo);

    }

    private void addUsuario() {

        /* if (txtIdUsuario.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Campo idusuario Invalido");
         txtIdUsuario.grabFocus();
         return;
         } else*/ 
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo nome Invalido");
            txtNome.grabFocus();
            return;
        } else if (txtCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo cpf Invalido");
            txtCpf.grabFocus();
            return;
        } else if (txtTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo telefone Invalido");
            txtTelefone.grabFocus();
            return;
        }else if (txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo estado Invalido");
            txtEstado.grabFocus();
            return;
        } else if (txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo cidade Invalido");
            txtEstado.grabFocus();
            return;
        } else if (txtEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo endereco Invalido");
            txtEndereco.grabFocus();
            return;
        } else if (txtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo bairro Invalido");
            txtBairro.grabFocus();
            return;
        } else if (txtNumeroCarteira.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo numerocarteira Invalido");
            txtNumeroCarteira.grabFocus();
            return;
        } else if (txtTipoCarteira.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo tipocarteira Invalido");
            txtTipoCarteira.grabFocus();
            return;
        }
        if (usuario == null) {
            usuario = new Usuario();
        }

        //usuario.setIdUsuario(Integer.parseInt(txtIdUsuario.getText()));
        usuario.setNome(txtNome.getText());
        usuario.setCpf(txtCpf.getText());
        usuario.setTelefone(txtTelefone.getText());
        usuario.setEstado(txtEstado.getText());
        usuario.setCidade(txtCidade.getText());
        usuario.setEndereco(txtEndereco.getText());
        usuario.setBairro(txtBairro.getText());
        usuario.setNumeroCarteira(txtNumeroCarteira.getText());
        usuario.setTipoCarteira(txtTipoCarteira.getText());

        if (usuarioController.insereUsuario(usuario)) {
            insereTabela(usuario);
            limpaCampos();
            listaUsuario();

        }
    }

    public void insereTabela(Usuario usuario) {
        Object[] linha = new Object[10];
        linha[0] = usuario.getIdUsuario();
        linha[1] = usuario.getNome();
        linha[2] = usuario.getCpf();
        linha[3] = usuario.getTelefone();
        linha[4] = usuario.getEstado();
        linha[5] = usuario.getCidade();
        linha[6] = usuario.getEndereco();
        linha[7] = usuario.getBairro();
        linha[8] = usuario.getNumeroCarteira();
        linha[9] = usuario.getTipoCarteira();
        modelo.addRow(linha);
    }

    public void listaUsuario() {
        setModelo();
        ArrayList<Usuario> lista;
        lista = usuarioController.getUsuarios();
        for (int x = 0; x < lista.size(); x++) {
            Usuario us = lista.get(x);
            insereTabela(us);
        }
        listaUsuario = lista;
    }

    private void limpaCampos() {
        usuario = null;

        
        txtNome.setText("");
        txtCpf.setText("");
        txtTelefone.setText("");
        txtEstado.setText("");
        txtCidade.setText("");
        txtEndereco.setText("");
        txtBairro.setText("");
        txtNumeroCarteira.setText("");
        txtTipoCarteira.setText("");
        txtNome.grabFocus();
    }

    private int pegaIdSelecionado() {
        int linha = tblCadastro.getSelectedRow();
        return Integer.parseInt(modelo.getValueAt(linha, 0).toString());
    }

    private void deleteUsuario() {
        int numero = pegaIdSelecionado();
        String id = null;
        JOptionPane.showMessageDialog(null, "Deletando usuario de nome: " + id);
        usuarioController.deleteUsuario(numero);
        listaUsuario();
    }

    private void carregaUsuario() {
        int id = pegaIdSelecionado();
        for (int x = 0; x < listaUsuario.size(); x++) {
            Usuario us = listaUsuario.get(x);
            if (id == us.getIdUsuario()) {

                
                txtNome.setText(us.getNome());
                txtCpf.setText(us.getCpf() + "");
                txtTelefone.setText(us.getTelefone() + "");
                txtEstado.setText(us.getEstado());
                txtCidade.setText(us.getCidade());
                txtEndereco.setText(us.getEndereco());
                txtBairro.setText(us.getBairro());
                txtNumeroCarteira.setText(us.getNumeroCarteira() + "");
                txtTipoCarteira.setText(us.getTipoCarteira());
                usuario = us;
                break;
            }
        }
    }

}

