/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RotaController;
import controller.VeiculoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Rota;
import model.Veiculo;

/**
 *
 * @author Senai
 */
public class TelaRota extends javax.swing.JInternalFrame {

    RotaController rotaController;
    ArrayList<Rota> listaRota;
    Rota rota;

    /**
     * Creates new form TelaRota
     */
    public TelaRota() {
        initComponents();
        setModelo();
        limpaCampos();
        rotaController = new RotaController();
        listaRota();
        this.setSize(530, 470);
        this.setLocation(80, 320);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSaida = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtDistanciaPercorrida = new javax.swing.JTextField();
        txtGastosExtras = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastro = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Rotas");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("     Cadastros de Rotas");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Local de saída:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Destino:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Distância Percorrida:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Gastos Extras:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        txtSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaidaKeyTyped(evt);
            }
        });

        txtDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestinoKeyTyped(evt);
            }
        });

        txtDistanciaPercorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanciaPercorridaActionPerformed(evt);
            }
        });
        txtDistanciaPercorrida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistanciaPercorridaKeyTyped(evt);
            }
        });

        txtGastosExtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGastosExtrasKeyTyped(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tblCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadastro);

        btnExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(btnLimpar)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(txtSaida)
                                    .addComponent(txtDistanciaPercorrida)
                                    .addComponent(txtGastosExtras)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDistanciaPercorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGastosExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDistanciaPercorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanciaPercorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanciaPercorridaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        addRota();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        deleteRota();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtSaidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaidaKeyTyped
        if (evt.getKeyChar() == 10) {
            txtDestino.grabFocus();
        }
    }//GEN-LAST:event_txtSaidaKeyTyped

    private void txtDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyTyped
        if (evt.getKeyChar() == 10) {
            txtDistanciaPercorrida.grabFocus();
        }
    }//GEN-LAST:event_txtDestinoKeyTyped

    private void txtDistanciaPercorridaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistanciaPercorridaKeyTyped
        if (evt.getKeyChar() == 10) {
            txtGastosExtras.grabFocus();
        }
    }//GEN-LAST:event_txtDistanciaPercorridaKeyTyped

    private void txtGastosExtrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGastosExtrasKeyTyped
        if (evt.getKeyChar() == 10) {
            btnCadastrar.grabFocus();
        }
    }//GEN-LAST:event_txtGastosExtrasKeyTyped

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
      
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void tblCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastroMouseClicked
      carregaRota();
    }//GEN-LAST:event_tblCadastroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCadastro;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDistanciaPercorrida;
    private javax.swing.JTextField txtGastosExtras;
    private javax.swing.JTextField txtSaida;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel modelo;

    private void setModelo() {

        modelo = new DefaultTableModel();
        modelo.addColumn("rotaId");
        modelo.addColumn("saida");
        modelo.addColumn("destino");
        modelo.addColumn("distanciaPercorrida");
        modelo.addColumn("gastosExtras");
        tblCadastro.setModel(modelo);

    }

    private void addRota() {

        /*if (txtRotaId.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Campo RotaId Invalido");
         txtRotaId.grabFocus();
         return;
         } else */ if (txtSaida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Saida Invalido");
            txtSaida.grabFocus();
            return;
        } else if (txtDestino.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Destino Invalido");
            txtDestino.grabFocus();
            return;
        } else if (txtDistanciaPercorrida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Distancia percorrida Invalido");
            txtDistanciaPercorrida.grabFocus();
            return;
        } else if (txtGastosExtras.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Gastos Extras Invalido");
            txtGastosExtras.grabFocus();
            return;
        }
        if (rota == null) {
            rota = new Rota();
        }

        //rota.setRotaId(Integer.parseInt(txtRotaId.getText()));
        rota.setSaida(txtSaida.getText());
        rota.setDestino(txtDestino.getText());
        rota.setDistanciaPercorrida(txtDistanciaPercorrida.getText());
        rota.setGastosExtras(txtGastosExtras.getText());
        if (rotaController.insereRota(rota)) {
            insereTabela(rota);
            limpaCampos();
            listaRota();
        }
    }

    public void insereTabela(Rota rota) {
        Object[] linha = new Object[10];
        linha[0] = rota.getRotaId();
        linha[1] = rota.getSaida();
        linha[2] = rota.getDestino();
        linha[3] = rota.getDistanciaPercorrida();
        linha[4] = rota.getGastosExtras();
        modelo.addRow(linha);
    }

    public void listaRota() {
        setModelo();
        ArrayList<Rota> lista;
        lista = rotaController.getRota();
        for (int x = 0; x < lista.size(); x++) {
            Rota ro = lista.get(x);
            insereTabela(ro);
        }
        listaRota = lista;
    }

    private void limpaCampos() {
        rota = null;

        txtSaida.setText("");
        txtDestino.setText("");
        txtDistanciaPercorrida.setText("");
        txtGastosExtras.setText("");
    }

    private int pegaIdSelecionado() {
        int linha = tblCadastro.getSelectedRow();
        return Integer.parseInt(modelo.getValueAt(linha, 0).toString());
    }

    private void deleteRota() {
        int numero = pegaIdSelecionado();
        String id = null;
        JOptionPane.showMessageDialog(null, "Deletando rota de nome: " + id);
        rotaController.deleteRota(numero);
        listaRota();
    }

    private void carregaRota() {
        int id = pegaIdSelecionado();
        for (int x = 0; x < listaRota.size(); x++) {
            Rota ro = listaRota.get(x);
            if (id == ro.getRotaId()) {

                txtSaida.setText(ro.getSaida());
                txtDestino.setText(ro.getDestino());
                txtDistanciaPercorrida.setText(ro.getDistanciaPercorrida());
                txtGastosExtras.setText(ro.getGastosExtras());
                rota = ro;
                break;
            }
        }
    }

}
